server:
  port: 8082

spring:
  profiles:
    ## prod:生产环境，dev:开发环境
    active: dev
    ## kafka,rabbit 配置
    include: rabbit-amqp-dev
  application:
    name: geer2-iot-core
  ## 解决springboot2.1.x后@FeignClient相同名字报错问题
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB

  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:com/geer2/**/mapper/*.xml
  type-aliases-package: com.geer2.**.entity
  configLocation: classpath:mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true

# 打印sql
logging:
  level:
    com.geer2.**.mapper: DEBUG

#Spring Cloud 服务注册
eureka:
  instance:
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 30
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Spring Cloud 服务消费者
feign:
  hystrix:
    enabled: true

#熔断器超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #断路器的超时时间需要大于Ribbon的超时时间
            timeoutInMilliseconds: 60000

ribbon:
  #ribbon请求连接的超时时间- 限制X秒内必须请求到服务，并不限制服务处理的返回时间
  ConnectTimeout: 40000
  #请求处理的超时时间 下级服务响应最大时间,超出时间消费方（路由也是消费方）返回timeout
  ReadTimeout: 50000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: false
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 0
  #对当前实例的重试次数
  MaxAutoRetries: 0
